modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "skillexpnotifier"
version = "${version}"
displayName = "SkillExpNotifier"
authors = "space_mex"
description = '''
A Simple Highly Customizable Toast For Puffish Skill Api
'''
#logoFile = ""

[[dependencies.skillexpnotifier]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skillexpnotifier]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skillexpnotifier]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.skillexpnotifier]]
modId = "puffish_skills"
mandatory = true
versionRange = "[0.16.0,)"
